name: Manual update
on: workflow_dispatch
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch content
        run: ./curl.sh < url.txt

      - name: Commit and push if changed
        run: |
          git config --global user.email "runner@example.com"
          git config --global user.name "runner"
          git add -A
          git commit -m "Update data" || exit 0
          git push
