name: Manual update
on: workflow_dispatch
jobs:
  fetch:
    strategy:
      matrix:
        foo: [x00, x01, x02, x03, x04]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch content
        run: |
          export FOO=${{ matrix.foo }}
          mkdir -p out/${{ matrix.foo }}
          curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.3" \
            --parallel --remote-name-all --output-dir "out/$FOO" -L $(cat ${{ matrix.foo }})
          zip -r out/${{ matrix.foo }}.zip out/${{ matrix.foo }}
      - name: Push artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.foo }}.zip
          path: out/${{ matrix.foo }}.zip
