name: Manual update
on: workflow_dispatch
jobs:
  fetch:
    strategy:
      matrix:
        foo: [x00, x01, x02, x03, x04]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch content
        run: |
          ./curl.sh < ${{ matrix.foo }}
      - name: Commit and push if changed
        run: |
          git config --global user.email "runner@example.com"
          git config --global user.name "runner"
          git add -A
          git commit -m "Update data ${{ matrix.foo }}" || exit 0
          git pull --rebase
          git push
