name: Manual update
on: workflow_dispatch
jobs:
  fetch:
    strategy:
      matrix:
        foo: [x00, x01, x02, x03, x04, x05, x06, x07, x08, x09]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch content
        run: |
          export FOO=${{ matrix.foo }}
          mkdir -p out/${{ matrix.foo }}
          ./curl.sh < ${{ matrix.foo }}
          zip -r out/${{ matrix.foo }}.zip out/${{ matrix.foo }}
      - name: Push artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.foo }}.zip
          path: out/${{ matrix.foo }}.zip
